### ISSUE TITLE
关于实验五的一些疑问

### ISSUE THREAD

**Issue by zzzcola** [MiChuan/RFID#1]
请问为什么运行您的承租以后，虽然能够正常编译出ui界面，并且显示连接成功，但是刷卡无法显示注册界面，这个问题怎么解决？
而且我如何能够获取管理员的权限呢 求教

**Comment by MiChuan** [comment]
管理员账号和密码在 lab5/Library/pages/login.cpp 中的构造函数设置（16,17行），从本地配置文件读取， 配置文件路径在 lab5/Library/tools/config.ini

**Comment by zzzcola** [comment]
请问按照您给出的方法配置好管理员账号密码之后会报错用户不存在，控制台报错数据库打开失败，请问这是什么原因

**Comment by zzzcola** [comment]
配置文件路径更改之后，会显示密码错误

**Comment by zzzcola** [comment]
按理说不应该会出现只存在用户名但是密码错误的情况orz

**Comment by MiChuan** [comment]
不要移动配置文件到其他地方，读取配置文件用的相对路径，在 lab5/Library/pages/login.cpp 112行调用了 lab5/Library/tools)/useraccount.cpp里的MD5加密函数，输入框输入的密码会使用这个哈希函数加密后与配置文件里的比较，你可以使用在线的MD5工具根据明文密码生成加密后的值，也可以调试这个函数获取值，然后替换配置文件的密码

**Comment by zzzcola** [comment]
原来是加密了orz，通过调试已经能够正常登录了，感谢
